# Generated by Django 3.0.3 on 2020-02-22 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_code', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=48, unique=True)),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('professor_name', models.CharField(max_length=48)),
                ('professor_email', models.EmailField(max_length=48, unique=True)),
                ('professor_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=48)),
                ('student_email', models.EmailField(max_length=48, unique=True)),
                ('student_password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('teaching_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=8)),
                ('academic_semester', models.CharField(max_length=4)),
                ('module_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Module')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Professor')),
            ],
            options={
                'db_table': 'teaching',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(max_length=4)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Student')),
                ('teaching_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Teaching')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
