# Generated by Django 3.0.3 on 2020-02-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='professor_email',
            field=models.EmailField(max_length=48, null=True, unique=True),
        ),
    ]
