# Generated by Django 3.0.3 on 2020-02-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200223_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='academic_semester',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='academic_year',
            field=models.IntegerField(max_length=8),
        ),
    ]
