# Generated by Django 3.0.3 on 2020-02-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200223_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='academic_semester',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2')]),
        ),
    ]
