# Generated by Django 3.0.3 on 2020-03-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200223_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='login_state',
            field=models.IntegerField(default=0),
        ),
    ]
