# Generated by Django 3.0.3 on 2020-03-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_student_login_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
